# Map Editor Routes

map_request_bounds:
  path: /event/map/edit/request/bounds
  defaults: { _controller: ManagerBundle:MapEditor:getBounds }

map_request_sub_tool:
  path: /event/map/edit/request/subtool/{type}
  defaults: { _controller: ManagerBundle:MapEditor:getSubtool }

map_request_save:
  path: /event/map/edit/request/save
  defaults: { _controller: ManagerBundle:MapEditor:Save }

map_request_image_upload:
  path: /event/map/edit/request/image/upload
  defaults: { _controller: ManagerBundle:MapEditor:uploadImage }
  requirements:
          _method:  POST

map_request_uploaded_images:
  path: /event/map/edit/request/image/get
  defaults: { _controller: ManagerBundle:MapEditor:getUploadedImages }

map_request_delete_image:
  path: /event/map/edit/request/image/delete/{id}
  defaults: { _controller: ManagerBundle:MapEditor:deleteImage }

map_request_mapobject_info_show:
  path: /event/map/edit/request/object_info/show
  defaults: { _controller: ManagerBundle:MapEditor:showObjectInfo }

map_request_mapobject_editor:
  path: /event/map/edit/request/map_object_editor
  defaults: { _controller: ManagerBundle:MapEditor:mapObjectEditor }

map_request_mapobject_price_entry_save:
  path: /event/map/edit/map_object/entry/price/save
  defaults: { _controller: ManagerBundle:MapEditor:priceEntrySave }

map_request_mapobject_price_entry_delete:
  path: /event/map/edit/map_object/entry/price/delete
  defaults: { _controller: ManagerBundle:MapEditor:priceEntryDelete }