# Old entries, need converting to new url format!

map_sub_tool:
  path: /editor/subtool/{type}
  defaults: { _controller: ManagerBundle:MapEditor:getSubtool }

map_object_editor:
  path: /editor/object_editor/{type}
  defaults: { _controller: ManagerBundle:MapEditor:mapObjectEditor }

# New Entries!

##################################################
#               Image  Routes                    #
##################################################

map_image_uploads:
  path: /editor/image/get
  defaults: { _controller: ManagerBundle:MapEditorImage:getUploads }

map_image_upload:
  path: /editor/image/upload
  defaults: { _controller: ManagerBundle:MapEditorImage:upload }
  requirements:
    _method:  POST

map_image_delete:
  path: /editor/image/delete/{id}
  defaults: { _controller: ManagerBundle:MapEditorImage:delete }

##################################################
#             Map Object Routes                  #
##################################################

map_object_save:
  path: /editor/object/save
  defaults: { _controller: ManagerBundle:MapEditorAction:saveObject }
  requirements:
      _method:  POST

map_object_delete:
  path: /editor/object/delete
  defaults: { _controller: ManagerBundle:MapEditorAction:deleteObject }
  requirements:
      _method:  POST


##################################################
#         Map Object Entry Routes                #
##################################################

map_entry_save:
  path: /editor/entry/save/{type}
  defaults: { _controller: ManagerBundle:MapEditorAction:saveEntry }
  requirements:
    _method:  POST

map_entry_delete:
  path: /editor/entry/delete/{type}
  defaults: { _controller: ManagerBundle:MapEditorAction:deleteEntry }
  requirements:
    _method:  POST

object_info_show:
  path: /editor/object_info/show/{id}
  defaults: { _controller: ManagerBundle:MapEditorTemplate:objectInfo }

##################################################
#             Map Loading Routes                 #
##################################################

map_load:
  path: /editor/load
  defaults: { _controller: ManagerBundle:MapEditorAction:load }