# Login Routes
login:
    pattern:  /
    defaults: { _controller: ManagerBundle:Default:index }

login_check:
    pattern: /login_check

logout:
    pattern:   /logout

# Account Routes
account_register:
    path:     /register
    defaults: { _controller: ManagerBundle:Account:register }
account_create:
    path:     /register/create
    defaults: { _controller: ManagerBundle:Account:create }

