# Old entries, need converting to new url format!

map_request_sub_tool:
  path: /event/map/edit/request/subtool/{type}
  defaults: { _controller: ManagerBundle:MapEditor:getSubtool }

map_request_image_upload:
  path: /event/map/edit/request/image/upload
  defaults: { _controller: ManagerBundle:MapEditor:uploadImage }
  requirements:
    _method:  POST

map_request_uploaded_images:
  path: /event/map/edit/request/image/get
  defaults: { _controller: ManagerBundle:MapEditor:getUploadedImages }

map_request_delete_image:
  path: /event/map/edit/request/image/delete/{id}
  defaults: { _controller: ManagerBundle:MapEditor:deleteImage }

map_request_mapobject_info_show:
  path: /event/map/edit/request/object_info/show
  defaults: { _controller: ManagerBundle:MapEditor:showObjectInfo }

map_request_mapobject_editor:
  path: /event/map/edit/request/map_object_editor
  defaults: { _controller: ManagerBundle:MapEditor:mapObjectEditor }

# New Entries!

##################################################
#             Map Object Routes                  #
##################################################

map_object_save:
  path: /editor/object/save
  defaults: { _controller: ManagerBundle:MapEditorAction:saveObject }
  requirements:
      _method:  POST

map_object_delete:
  path: /editor/object/delete
  defaults: { _controller: ManagerBundle:MapEditorAction:deleteObject }
  requirements:
      _method:  POST


##################################################
#         Map Object Entry Routes                #
##################################################

map_entry_save:
  path: /editor/entry/save/{type}
  defaults: { _controller: ManagerBundle:MapEditorAction:saveEntry }
  requirements:
    _method:  POST

map_entry_delete:
  path: /editor/entry/delete/{type}
  defaults: { _controller: ManagerBundle:MapEditorAction:deleteEntry }
  requirements:
    _method:  POST

##################################################
#             Map Loading Routes                 #
##################################################

map_load:
  path: /editor/load
  defaults: { _controller: ManagerBundle:MapEditorAction:load }